### ISSUE TITLE
Support quoted strings

### ISSUE THREAD

**Issue by OmgImAlexis** [loge5/conf-cfg-ini#1]
Any chance you could add support for quotes around the section and/or the value. For example I have a few files I need to read that must keep the formatting they're using these two seperate formats.

```
[confirm]
down="1"
stop="1"
```

```
["display"]
sb="15"
```

**Comment by loge5** [comment]
I added for you the option "valueIdentifier".
So for your example you can set it like this:

```javascript
var config = new Config();
// for the values
config.options.valueIdentifier = '"';
// and for the sections:
config.options.sectionOpenIdentifier =  '["';
config.options.sectionCloseIdentifier: '"]',
// ...
```

Just update to Version 1.1.0

**Comment by OmgImAlexis** [comment]
Sorry if that was a waste of time. 😞 

I had a bit of time today so I've actually added this myself as well as converting the package to ES6 if you wanted to check it out.

https://github.com/OmgImAlexis/conf-cfg-ini
