### ISSUE TITLE
How can i read this cfg file?

### ISSUE THREAD

**Issue by alimsahy** [loge5/conf-cfg-ini#2]
Hi,

I have external .cfg file which is shared with another program. I already read documentation but my codes doesn't work. 

![image](https://user-images.githubusercontent.com/5039536/65756496-e0016600-e11d-11e9-8547-fec08f7ac0c4.png)
This .cfg file has unordered whitespace between key and value. I tried to read this file using this code.

```javascript
var config = new configuration();
config.options.assignIdentifier = '[\t]+'; // also tried to use \s and  " "
config.options.defaultValue = null;
config.options.commentIdentifiers = [';'];
config.options.trimLines = true;

var raw = fileSystem.readFileSync(application.app.getAppPath() + '/file.cfg');
config.options.lineEnding = config.detectLineEnding(raw);
var configObject = config.decode(raw);

console.log(configObject);
```
When I start the application, it reads the key and values in the .cfg file as a single key. How can i fix this? 

Thanks.

**Comment by loge5** [comment]
Hi,

I assume with  "unordered whitespace"  you mean a different number of horizontal tabs (\t) each line.
Example:
```
SOFTWARE_TILING\t2
SHADOW_LEVEL\t\t0
```

Since `assignIdentifier` is not a regex you can only do something like this:

```javascript
config.options.assignIdentifier = '\t';
```
but than you have to trim the values by your self.


For now I would suggest to unify the file content before decode:
```javascript
raw = raw.toString().replace(/\t+/, '\t')
```

**Comment by loge5** [comment]
I was thinking about implementing a feature for this problem.

Allowing regex for the `assignIdentifier` would not work for `encode`, which breaks the workflow "decode > edit > encode".

Maybe a new option like "combineMultipleAssignIdentifier" :thinking:

**Comment by loge5** [comment]
In Version 1.2.0 you can now use this:

```javascript
config.options.assignIdentifier = '\t';
config.options.ignoreMultipleAssignIdentifier = true;
```
