### ISSUE TITLE
How to prevent the default value from getting added?

### ISSUE THREAD

**Issue by shishiranshuman** [loge5/conf-cfg-ini#7]
Currently, when I run the code, the default value gets added as "=true".
What do I do if don't want to add the default value?

**Comment by loge5** [comment]
You could set the option to an empty string:

`config.options.defaultValue = ''`

This should result in something like this:

```
[SectionA]
withValue=1
withoutValue=
```

When you also do not want the equals sign, than I this lib can not handle this at the moment.
But you could do a simple string replace afterwards (Regex: `/=\n/`).
